#!/bin/bash

# This is not intended to be a working script, it is mearly an example of what developers can do
#GIT_USER_REPO="cynixx3/third-party-miner-installer-for-ethos"
#RELEASE_SHASUM="sha256sum of archive"
#MINER_ARCHIVE_FOLDER="Miner_Folder"
#DEPENDS="URL URL"
MINER_BRANCH="$1"
CMD="$0"
ACTION="$2"
TMP_DIR="/tmp/newminer"

# Get miner files and setup temporary opt/
f.PREPMINER(){
  echo "Getting latest release of miner"
  curl -s https://api.github.com/repos/$GIT_USER_REPO/releases \
  | grep -i "browser_download_url.*$MINER_BRANCH.*tar\..z" \
  | cut -d '"' -f 4 \
  | head -1 \
  | wget -qi - -O "$MINER_BRANCH.tar.gz"

  echo "Comparing download with checksum"
  if ! echo "$RELEASE_SHASUM $MINER_BRANCH.tar.gz" | sha256sum -c ; then
    echo "checksum of downloaded files failed, please try again or update miner.settings in repo"
    exit 3
  fi
  
  echo "Unpacking miner"
  if ! tar xzf "$TMP_DIR/$MINER_BRANCH.tar.gz" ; then
    echo "Unable to extract files package. please try again."
    exit 4
  fi
  
  mkdir -p "$TMP_DIR/opt/miners"
  rsync -a --delete "$TMP_DIR/$MINER_ARCHIVE_FOLDER/" "$TMP_DIR/opt/miners/$MINER_BRANCH"
  
  echo "Temporary miner files ready"
}

# Prevent package lock when installing dependencies
f.CHECKDPKG(){
  DPKGLOCKED=$(lsof /var/lib/dpkg/lock 2>/dev/null | grep -c "/var/lib/dpkg/lock")
  WAITCOUNT="0"
  if [ "$DPKGLOCKED" -ge "1" ]; then
    until [ "$DPKGLOCKED" = "0" ] || [ "$WAITCOUNT" = "60" ]; do
      DPKGLOCKED=$(lsof /var/lib/dpkg/lock 2>/dev/null | grep -c "/var/lib/dpkg/lock")
      ((WAITCOUNT++))
    done
  fi
  if [ "$WAITCOUNT" -ge "120" ]; then
    echo "Timed out waiting on dpkg lock to clear."
    echo "manually clearing dpkg lock"
    rm -f /var/lib/dpkg/lock
  fi
}

# Get Replacement ethos files that enable miner operation and install miner specific dependencies
f.PREPETHOS(){
  echo "Download and unpack files needed by ethOS"
#todo add ethos version checking
  git clone https://github.com/cynixx3/third-party-miner-installer-for-ethos.git -b "$MINER_BRANCH"
  
  mkdir -p $TMP_DIR/opt/ethos
  rsync -a --delete "$TMP_DIR/third-party-miner-installer-for-ethos/opt/ethos/" "$TMP_DIR/opt/ethos"
  chmod 775 "$TMP_DIR"/opt/ethos/bin/* "$TMP_DIR"/opt/ethos/sbin/* 
  chmod 744 "$TMP_DIR"/opt/ethos/etc/*
  if [ -f "$TMP_DIR"/opt/ethos/lib/minerprocess.php ] ; then
    chmod 644 "$TMP_DIR"/opt/ethos/lib/minerprocess.php
  fi
  if [ -f  "$TMP_DIR"/opt/ethos/lib/functions.php ] ; then
    chmod 755 "$TMP_DIR"/opt/ethos/lib/functions.php
  fi

  echo "Check for dependencies"
  if [ "$DEPENDS" ] ; then
    echo "Installing dependencies"
    mkdir "$TMP_DIR/depends"
    for URL in ${DEPENDS[@]} ; do
      wget $URL -P depends
    done
    f.CHECKDPKG
    sudo dpkg --configure -a
    f.CHECKDPKG
    sudo dpkg -i "$TMP_DIR"/depends/*.deb
  fi
  
  echo "ethOS files ready"
}

# Gather stock ethOS files in temporary opt/ and install stock packages
f.REVERT(){
#todo add ethos version checking
  git clone https://github.com/cynixx3/third-party-miner-installer-for-ethos.git -b ethos-1.3.3
  mkdir -p "$TMP_DIR/opt/ethos"
  rsync -a --delete "$TMP_DIR/third-party-miner-installer-for-ethos/opt/ethos/" "$TMP_DIR/opt/ethos"
  chmod 775 "$TMP_DIR"/opt/ethos/bin/* "$TMP_DIR"/opt/ethos/sbin/* 
  chmod 744 "$TMP_DIR"/opt/ethos/etc/*
  if [ -f "$TMP_DIR"/opt/ethos/lib/minerprocess.php ] ; then
    chmod 644 "$TMP_DIR"/opt/ethos/lib/minerprocess.php
  fi
  if [ -f  "$TMP_DIR"/opt/ethos/lib/functions.php ] ; then
    chmod 755 "$TMP_DIR"/opt/ethos/lib/functions.php
  fi
# Reinstall stock dependencies
#todo add ethos version checking
  mkdir "$TMP_DIR/depends"
  wget http://security.ubuntu.com/ubuntu/pool/main/g/gcc-4.8/gcc-4.8-base_4.8.4-2ubuntu1~14.04.4_amd64.deb -P depends
  wget https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test/+build/14981774/+files/gcc-8-base_8.1.0-5ubuntu1~14.04_amd64.deb -P depends
  f.CHECKDPKG
  sudo dpkg --configure -a
  f.CHECKDPKG
  sudo dpkg -i "$TMP_DIR"/depends/*.deb
}

f.INSTALL(){
  echo "Stopping the miner"
  /opt/ethos/bin/disallow
  /opt/ethos/bin/minestop
  
  echo "Installing miner"
  sudo rsync -av "$TMP_DIR/opt/" /opt
  sudo chown -R ethos.ethos /opt/miners/
  
  echo "Restarting services and miner"
  sudo service ethos-miner-daemon restart
  sudo service ethos-stats-daemon restart
  sudo service ethos-gpu-stats-daemon restart
  /opt/ethos/bin/allow
}

f.CLEANUP(){
  rm -rf "$TMP_DIR"
}

f.HELP (){
  echo "$1
Usage $CMD [miner] ( install | update | revert )

Miners Available:
$(curl -s https://api.github.com/repos/cynixx3/third-party-miner-installer-for-ethos/branches | grep name | cut -d '"' -f 4 | grep -Ev '(1.3|master)')"
}

# TODO add logging
if [ "$#" -ne "2" ] ; then
  f.HELP "Wrong number of arguments"
  exit 1
elif [[ "$(curl -s https://api.github.com/repos/cynixx3/third-party-miner-installer-for-ethos/branches | grep name | cut -d '"' -f 4 | grep -Ev '(1.3|master)')" == *" $MINER_BRANCH "* ]] ; then
  f.HELP "Invalid miner selected, Please choose from the list below"
  exit 2
fi

# Get miner settings
source <(curl -s https://raw.githubusercontent.com/cynixx3/third-party-miner-installer-for-ethos/$MINER_BRANCH/miner.settings)

echo "Move to a temporary work space"
mkdir "$TMP_DIR"
cd "$TMP_DIR" || exit

case "$2" in
  install)
    f.PREPMINER
    f.PREPETHOS
    f.INSTALL
    f.CLEANUP
  ;;
  update)
    f.PREPMINER
    f.INSTALL
    f.CLEANUP
  ;;
  revert)
    f.REVERT
    rm -rf "/opt/miners/$MINER_BRANCH"
    f.INSTALL
    f.CLEANUP
  ;;
  *)
    f.HELP "Invalid action, options are install, update, or revert"
    exit 3
esac
cd ~ || exit
