#!/bin/bash

# This is not intended to be a working script, it is merely an example of what developers can do
TMP_DIR=/tmp/newminer
echo "Move to a temporary work space"
mkdir $TMP_DIR
cd $TMP_DIR

f.prepminer(){
  echo "Getting latest release of miner"
  wget http://update.ethosdistro.com/miners/xmr-stak/xmr-stak-2.7.1.tar.xz
  echo "Comparing download with checksum"
  echo "E57CA2AB960B8C7899020E4827DB8A5CC90CA45FE96B030C97BF9570D9AE4C26 xmr-stak-2.7.1.tar.xz" | sha256sum -c 
  if [ "$?" -ne "0" ]; then echo "checksum of downloaded files failed, please try again";exit 1; fi
  
  echo "Unpacking miner"
  tar xzf $TMP_DIR/xmr-stak-2.7.1.tar.xz -C $TMP_DIR/xmr-stak-2.7.1
  if [ "$?" != "0" ]; then
    echo "Unable to extract files package. please try again."
    exit 2
  fi

  rsync -a --delete $TMP_DIR/xmr-stak-2.7.1/ $TMP_DIR/opt/miners/xmr-stak
  
  echo "Temporary miner files ready"
}

f.checkdpkg(){
  DPKGLOCKED=$(lsof /var/lib/dpkg/lock 2>/dev/null | grep -c "/var/lib/dpkg/lock")
  WAITCOUNT="0"
  if [ "$DPKGLOCKED" -ge "1" ]; then
    until [ "$DPKGLOCKED" = "0" ] || [ "$WAITCOUNT" = "60" ]; do
      DPKGLOCKED=$(lsof /var/lib/dpkg/lock 2>/dev/null | grep -c "/var/lib/dpkg/lock")
      ((WAITCOUNT++))
    done
  fi
  if [ "$WAITCOUNT" -ge "120" ]; then
    echo "Timed out waiting on dpkg lock to clear."
    echo "manually clearing dpkg lock"
    rm -f /var/lib/dpkg/lock
  fi
}

f.prepethos(){
  echo "Download and unpack files needed by ethOS"
  git clone https://github.com/cynixx3/third-party-miner-installer-for-ethos.git -b xmr-stak
  
  mkdir -p $TMP_DIR/opt/ethos
  rsync -a --delete $TMP_DIR/third-party-miner-installer-for-ethos/opt/ethos/ $TMP_DIR/opt/ethos
  chmod ug+x $TMP_DIR/opt/ethos/*

  echo "ethOS files ready"
}

f.revert(){
  git clone https://github.com/cynixx3/third-party-miner-installer-for-ethos.git -b ethos-1.3.3
  mkdir -p $TMP_DIR/opt/ethos
  rsync -a --delete $TMP_DIR/third-party-miner-installer-for-ethos/opt/ethos/ $TMP_DIR/opt/ethos
  chmod ug+x $TMP_DIR/opt/ethos/lib/* $TMP_DIR/opt/ethos/bin/* $TMP_DIR/opt/ethos/sbin/*
  chmod u+x $TMP_DIR/opt/ethos/etc/*
}